#!/bin/bash

# Set up environment variables for access to a specified XNAT database and archive
# Currently supported XNAT databases are ConnectomeDB and IntraDB
# Specified database is converted to lowercase before checking. So that specification
# is case insensitive.
# Author: Timothy B. Brown (tbbrown@wustl.edu)
# Creation Date: 21 Nov 2017
# Last Modification Date: 14 May 2018

requested_db="$(echo ${1} | tr '[:upper:]' '[:lower:]')"
if [ -z "${2}" ]; then
	unset silence_requested
elif [ "${2}" == "-s" ]; then
	silence_requested="TRUE"
else
	echo "Unrecognized second parameter: ${2}"
	echo ""
	echo "xnat_pbs_setup: ERROR:"
	echo "xnat_pbs_setup: ERROR: Unrecognized <silence-request>: ${2}"
	echo "xnat_pbs_setup: ERROR: Please specify -s or leave second parameter unspecified"
	echo "xnat_pbs_setup: ERROR:"
fi

export SINGULARITY_CONTAINER_VERSION=singularity-2.5.2
export SINGULARITY_BIND_PATH=/HCP/hcpdb/build_ssd
export SINGULARITY_CONTAINER_PATH=/HCP/hcpdb/build_ssd/chpc/BUILD/junilc/MR_TEST/Test_sample_Test/single_RR6_min6.simg
export SINGULARITY_CONTAINER_XNAT_PATH=/HCP/hcpdb/build_ssd/chpc/BUILD/junilc/MR_TEST/Test_sample_Test/single_RR6_xnat_only.simg
#export SINGULARITY_CONTAINER_VERSION=singularity-3.0.0
#export SINGULARITY_BIND_PATH=/HCP/hcpdb/build_ssd
#export SINGULARITY_CONTAINER_PATH=/HCP/hcpdb/build_ssd/chpc/BUILD/junilc/MR_TEST/Test_sample_Test/single_RR7_single3.sif
#export SINGULARITY_CONTAINER_XNAT_PATH=/HCP/hcpdb/build_ssd/chpc/BUILD/junilc/MR_TEST/Test_sample_Test/single_RR7_XNAT_single3.sif

export GRADIENT_COEFFICIENT_PATH=/home/junilc/test_status/xnat_check/gradient_coefficient_files
export FREESURFER_LICENSE_PATH=/home/junilc/test_status/xnat_check/license

# Where data is placed outside of the archive for pipeline processing
# a.k.a. the "Build space"
# export XNAT_PBS_JOBS_BUILD_DIR=/home/${USER}/XNAT_BUILD_DIR/${USER}
export XNAT_PBS_JOBS_BUILD_DIR=${HOME}/XNAT_BUILD_DIR/${USER}

# Where log files that should NOT be pushed back into the archive
# after a pipeline runs should be stored.
# export XNAT_PBS_JOBS_LOG_DIR=/home/${USER}/XNAT_LOGS
export XNAT_PBS_JOBS_LOG_DIR=${HOME}/XNAT_LOGS

ln -sfn /HCP/hcpdb/build_ssd/chpc/BUILD ${HOME}/XNAT_BUILD_DIR
ln -sfn /HCP/hcpdb/build_ssd/chpc/logs/pbs/${USER} ${HOME}/XNAT_LOGS

if [ "${requested_db}" == "connectomedb" ]; then

	if [ -z "${silence_requested}" ]; then
		echo "xnat_pbs_setup: Setting up XNAT_PBS_JOBS environment to work with ConnectomeDB"
	fi

	# XNAT Archive
	export XNAT_PBS_JOBS_ARCHIVE_ROOT=/HCP/hcpdb/archive

	# Server name (URL minus the protocol specification) of the 
	# XNAT server with which to work
	export XNAT_PBS_JOBS_XNAT_SERVER=db.humanconnectome.org

	# Shadows Information
	export XNAT_PBS_JOBS_PUT_SERVER_LIST="10.28.58.180:8080 10.28.58.181:8080 10.28.58.182:8080"


elif [ "${requested_db}" == "intradb" ]; then

	if [ -z "${silence_requested}" ]; then
		echo "xnat_pbs_setup: Setting up XNAT_PBS_JOBS environment to work with IntraDB"
	fi

	# XNAT Archive
	export XNAT_PBS_JOBS_ARCHIVE_ROOT=/HCP/intradb/archive

	# Server name (URL minus the protocol specification) of the 
	# XNAT server with which to work
	export XNAT_PBS_JOBS_XNAT_SERVER=intradb.humanconnectome.org

	# Shadows Information
	export XNAT_PBS_JOBS_PUT_SERVER_LIST="10.28.58.153:8080 10.28.58.154:8080"

else

	echo "xnat_pbs_setup: ERROR:"
	echo "xnat_pbs_setup: ERROR: Unrecognized <db-spec>: ${1} --> ${requested_db}"
	echo "xnat_pbs_setup: ERROR: Please specify connectomedb or intradb (case insensitive)"
	echo "xnat_pbs_setup: ERROR:"

fi
